<?php include("config.php"); ?>
<!DOCTYPE html><html lang="en"><head>
<?php if($shopwebsite == "selly"){echo("<script src=\"http://embed.selly.io/\"></script>\n");}elseif($shopwebsite == "shoppy"){echo("<script src=\"https://shoppy.gg/api/embed.js\"></script>\n");}elseif($shopwebsite == "sellix"){echo("<script src=\"https://cdn.sellix.io/static/js/embed.js\"></script>\n");} ?>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><title><?php echo($websitetitle); ?></title><meta name="og:title" content="<?php echo($websitetitle); ?>"><meta name="description" content="<?php echo($websitedescription); ?>"><meta name="author" content="amboss#2199"><meta name="keywords" content="<?php echo($websitetags); ?>"><meta name="theme-color" content="light"><link rel="shortcut icon" href="favicon.ico" type="image/x-icon"><link rel="icon" href="favicon.ico" type="image/x-icon"><link href="vendor/bootstrap/css/bootstrap.css" rel="stylesheet"><link href="css/style.css" rel="stylesheet"><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous"><style>
body {overflow-y: scroll!important;}
.social-media {position: fixed;bottom: 10px;z-index:9;right: 25px}
.social-media a {-ms-transform: scale(1, 1);-webkit-transform: scale(1, 1);transform: scale(1, 1)}
.social-media a:hover {-ms-transform: scale(1.05, 1.05);-webkit-transform: scale(1.05, 1.05);transform: scale(1.05, 1.05)}
.social-media a {width: 60px;height: 60px;background: <?php echo($colorconfig[5]); ?>;display: block;text-align: center;line-height: 60px;font-size: 20pt;color: #fff!important;border-radius: 100px;margin-bottom: 15px;transition: all .15s ease-in-out;-moz-transition: all .15s ease-in-out;-webkit-transition: all .15s ease-in-out}
.social-media img {max-width: 32px;position: relative;top: -2px}
.btn-custom {background-color: <?php echo($colorconfig[1]); ?>;}
.overlay {background: <?php echo($colorconfig[0]); ?>;}
.bg-primary {background-color: <?php echo($colorconfig[0]); ?> !important;}
.card h5 {background: <?php echo($colorconfig[3]); ?>;}
.rezende-title:after {background: <?php echo($colorconfig[2]); ?>;}
a {color: <?php echo($colorconfig[4]); ?>;text-decoration: none;background-color: transparent;-webkit-text-decoration-skip: objects;}
</style></head><body><div class="social-media"><a href="<?php echo($discordlink); ?>" target="_blank"><img src="images/discordicon.png"></a></div><div class="not-fixed-top"> <nav class="navbar navbar-expand-lg navbar-dark bg-primary"> <div class="container"> <a class="navbar-brand" href="index.html"><?php echo($websitename); ?></a> <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button> <div class="collapse navbar-collapse" id="navbarResponsive"> <ul class="navbar-nav ml-auto"> <li class="nav-item active"> <a class="nav-link" href="index.php"> PURCHASE </a> </li><li class="nav-item"> <a class="nav-link" target="_blank" href="<?php echo($discordlink); ?>">DISCORD</a> </li></ul> </div></div></nav> <div class="overlay"></div></div><div class="container"> <div class="row"> <div class="col-lg-12"><br><div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel"> <ol class="carousel-indicators"> <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li><li data-target="#carouselExampleIndicators" data-slide-to="1"></li><li data-target="#carouselExampleIndicators" data-slide-to="2"></li></ol> <div class="carousel-inner active" role="listbox"> <div class="carousel-item active"> <img class="d-block img-fluid" src="<?php echo($sliderimages[0]); ?>" alt="Image 1"></div><div class="carousel-item"><img class="d-block img-fluid" src="<?php echo($sliderimages[1]); ?>" alt="Image 2"></div><div class="carousel-item"><img class="d-block img-fluid" src="<?php echo($sliderimages[2]); ?>" alt="Image 3"></div></div><a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev"><span class="carousel-control-prev-icon" aria-hidden="true"></span><span class="sr-only">Previous</span></a><a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next"><span class="carousel-control-next-icon" aria-hidden="true"></span><span class="sr-only">Next</span></a></div><div class="row">
<?php
foreach ($products as $category) {echo("<h1 class=\"rezende-title\"><b>" . $category[0] . "</b></h1>");echo("<div class=\"row\">");
foreach ($category[1] as $product) {echo("<div class=\"col-lg-4 col-md-6 mb-4\">");echo("<div class=\"card h-100\">");echo("<a data-" . $shopwebsite . "-product=\"" . $product[1] . "\" href=\"javascript:;\">");echo("<img class=\"card-img-top\" src=\"" . $product[2] . "\" alt=\"" . $product[0] . "\">");echo("</a>");echo("<div class=\"card-body\">");echo("<h4 class=\"card-title\">");echo("<a data-" . $shopwebsite . "-product=\"" . $product[1] . "\" href=\"javascript:;\">" . $product[0] . "</a>");echo("</h4>");echo("<h5>" . $product[3] . "</h5>");echo("<p class=\"card-text\">" . $product[4] . "</p>");echo("</div>");echo("<div class=\"card-footer\">");echo("<button data-" . $shopwebsite . "-product=\"" . $product[1] . "\" class=\"btn btn-custom\">" . $purchasetext . "</button>");echo("</div>        </div>        </div>");}}
?>
</div></div></div></div></div><footer class="py-5"><div class="container"><p class="m-0 text-center">Made  with ❤️ by <a style="color: #000;" href="https://www.fiverr.com/orel3030?up_rollout=true">orel#43789</a></p></div><br></footer><script src="vendor/jquery/jquery.min.js"></script><script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script></body></html>